/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppIcon: typeof import('./components/AppIcon.vue')['default']
    AppLogo: typeof import('./components/AppLogo.vue')['default']
    HeaderNavigationItem: typeof import('./components/Header/NavigationItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwapCard: typeof import('./components/Swap/Card.vue')['default']
    SwapContainer: typeof import('./components/Swap/Container.vue')['default']
    SwapLayout: typeof import('./components/Swap/layout.vue')['default']
    SwapNavButton: typeof import('./components/Swap/NavButton.vue')['default']
    SwapSelect: typeof import('./components/SwapSelect.vue')['default']
    WalletConnectButton: typeof import('./components/Wallet/ConnectButton.vue')['default']
  }
}
