/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBadge: typeof import('./components/AppBadge.vue')['default']
    AppButton: typeof import('./components/AppButton.vue')['default']
    AppDialog: typeof import('./components/AppDialog.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppIcon: typeof import('./components/AppIcon.vue')['default']
    AppInput: typeof import('./components/AppInput.vue')['default']
    AppLogo: typeof import('./components/AppLogo.vue')['default']
    HeaderNavigationItem: typeof import('./components/Header/NavigationItem.vue')['default']
    HexagonButtonBase: typeof import('./components/HexagonButton/Base.vue')['default']
    HexagonButtonClose: typeof import('./components/HexagonButton/Close.vue')['default']
    LightningButton: typeof import('./components/LightningButton.vue')['default']
    LoadingIcon: typeof import('./components/LoadingIcon.vue')['default']
    PentagonButtonBase: typeof import('./components/PentagonButton/Base.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwapCard: typeof import('./components/Swap/Card.vue')['default']
    SwapChoice: typeof import('./components/SwapChoice.vue')['default']
    SwapContainer: typeof import('./components/Swap/Container.vue')['default']
    SwapCurrencySelect: typeof import('./components/Swap/CurrencySelect.vue')['default']
    SwapDcaPriceRange: typeof import('./components/Swap/DcaPriceRange.vue')['default']
    SwapDcaSettings: typeof import('./components/Swap/DcaSettings.vue')['default']
    SwapLayout: typeof import('./components/Swap/layout.vue')['default']
    SwapNavButton: typeof import('./components/Swap/NavButton.vue')['default']
    SwapSelect: typeof import('./components/SwapSelect.vue')['default']
    WalletAddressButton: typeof import('./components/Wallet/AddressButton.vue')['default']
    SwapSelect: typeof import('./components/Swap/Select.vue')['default']
    SwapSelector: typeof import('./components/Swap/Selector.vue')['default']
    SwapSummary: typeof import('./components/Swap/Summary.vue')['default']
    WalletConnectButton: typeof import('./components/Wallet/ConnectButton.vue')['default']
    WalletConnectDialog: typeof import('./components/Wallet/ConnectDialog.vue')['default']
    WalletDialogConnectStatus: typeof import('./components/Wallet/DialogConnectStatus.vue')['default']
    WalletDisconnectDialog: typeof import('./components/Wallet/DisconnectDialog.vue')['default']
  }
}
