/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppIcon: typeof import('./components/AppIcon.vue')['default']
    AppLogo: typeof import('./components/AppLogo.vue')['default']
    HeaderNavigationItem: typeof import('./components/Header/NavigationItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WalletConnectButton: typeof import('./components/Wallet/ConnectButton.vue')['default']
  }
}
